### ISSUE TITLE
Game cache not updating on raspbian

### ISSUE THREAD

**Issue by powermeep** [zach-morris/plugin.program.iagl#164]
I've got a Retropie image, though I've configured it to boot into Kodi instead of emulationstation.
(Side bug, not sure if it's IAGL or something else, when Kodi is started via cron and I try to launch a game, it just kicks me back to the commandline. I suspect it's something related to environment variables)

I have IAGL set to keep the last 100 games. However, no matter what I set it to, it behaves as though the value is set to 0.
If I watch the addon_data folder, I can see the game I play and the save data that's created for it. However, next time I use IAGL, everything in the folder is purged and the next time I run the game will not have any save data or even state save data.

I have not tried reinstalling anything yet, but I'm running out of things to try.

**Comment by zach-morris** [comment]
Hmm.  I got nothing currently. A log may help (for both issues).
I will say there are several places cache is saved though:
```path_to_userdata/plugin.program.iagl/list_cache``` has the game history in it, along with other cached game lists (for faster loading)
```path_to_userdata/plugin.program.iagl/temp_iagl``` is the default location for game files to be downloaded to (although you can [change that](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to) in the settings)

**Comment by powermeep** [comment]
Is there a log just for IAGL? I don't see one in the plugin.program.iagl directory. I briefly scraped the previous two kodi logs and didn't really find anything that seemed helpful.

I updated the path for snes, played two games, and can confirm that they haven't been erased since using an external directory. The game history list, however, didn't update.

Another thing that happened during the test is that I caught a glimpse of emulationstation. It looked like my controller input was going to both the game and to ES, because it opened the Dreamcast menu in ES and then opened up a fullscreen blue menu, which was quickly replaced by the game again.

I'm really not sure what's happening and I'm starting to wonder if I should just do a clean Raspbian image and then install only kodi and retroarch onto it. I wonder if RetroPie is actually adding a layer of jank here.

**Comment by zach-morris** [comment]
The log is the Kodi log, with debug logging enabled in the Kodi settings.
I haven't actually used my addon in either a Retropie or Raspbian environment, so I'm not surprised it's not perfect.
The input issue is a known issue with an X-less setup and Kodi, which is why those setups typically have to run a shell script to close Kodi, run the game, and restart Kodi after the game is exited.  If both are open, there isn't any way for Kodi to know it's not in 'front' so it still recieves input.  In an X/window environment Kodi does know so it doesn't take the input.

The ideal way for this to work is for the game to be launched by a shell script that closes everything (ES, Kodi) and then launches the game, and after the game is exited, relaunches whatever was open previously.  I'm not entirely sure it does that currently.

**Comment by zach-morris** [comment]
I think this was related to [this](https://github.com/zach-morris/plugin.program.iagl/issues/187) issue where there was a conflict in writing to history, etc because Kodi was being shutdown via the launch script for the emulator.

I've updated this functionality in v3.0.0 (kodi v19), and i believe it works now.  If you still have issues please reopen
