### ISSUE TITLE
Amiga

### ISSUE THREAD

**Issue by D0GM4** [zach-morris/plugin.program.iagl#167]
Amiga games won’t open looking to see if there maybe a solution so I can possibly play an old favourite, appreciate any help

**Comment by zach-morris** [comment]
I would need a log to know the issue.  Although for Amiga, the issue is likely in the setup.  [Here's](https://github.com/zach-morris/plugin.program.iagl/issues/55) a previous issue that goes over a lot of problems with the Amiga core and setup

**Comment by coder9** [comment]
Hi, I've come across a similar problem and no matter how much I mess around with ROMs, WHDLoad, or settings files I can't get Amiga games to work.

Would I be right in saying that at the moment IAGL and Retroplayer don't work for Amiga games as the Amiga game lists were converted to point to the hdf versions and the current version of game.libretro.uae can't deal with hdfs so IAGL must be set up to call RetroArch?

The issue is here: https://github.com/kodi-game/game.libretro.uae/issues/2

**Comment by zach-morris** [comment]
I think this is fixed.  Several things changed:
Puae supports HDF more automatically now
The IAGL game lists are HDF games

I didn't exhaustively test, but the Amiga and Amiga CD32 games I tried worked great.  Give it a try with the new version of the addon, and reopen an issue with specifics if you still have issues.
