### ISSUE TITLE
Still getting the message "Archive returned no file or requires login in settings."

### ISSUE THREAD

**Issue by deadngone** [zach-morris/plugin.program.iagl#172]
For Atari 2600 games and Sega Saturn games. Even with login info on settings correctly. 
Please help.
![Screenshot_20200720-151925~2](https://user-images.githubusercontent.com/68557830/87972609-95cae600-ca9d-11ea-9e3b-c1c8ae9d899b.png)

**Comment by djay** [comment]
Same for dreamcast

**Comment by Craske** [comment]
Same problem here, Happening on windows pc and using a android box with coreelec.

If the saturn archive in use is the one i think it is, the uploader of the archive has recently removed the archive but poking around on the site there are other archives for saturn that are almost as complete.
Not sure if its the same story with atari 2600 and dreamcast.

**Comment by pirsir76** [comment]
Same here, I can't download Sega CD games because of this message.
My correct archive.org email and password have been inputted correctly.

**Comment by zach-morris** [comment]
I'm in the process of doing two things:
1) updating archives that have been modified or are no longer available for newer available archives
2) updating the messaging to split "not found" and "login is bad"

Specific to these archives:  Atari 2600, Sega Saturn, Sega CD archives have all since been deleted and I need to change the archives used.  As @Craske said, there appear to be several others, or the original archive was just moved to this new one for some reason.

**Comment by pirsir76** [comment]
Also, TurboGrafix CD is affected as well.

**Comment by zach-morris** [comment]
Fixed messaging in v19.  Updated all lists to newer versions so they're working.  Will release v19 shortly
