### ISSUE TITLE
Problems with xbmcvfs.translatepath in resources/lib/main.py

### ISSUE THREAD

**Issue by Cyber1000** [zach-morris/plugin.program.iagl#184]
Concerning this commit: https://github.com/zach-morris/plugin.program.iagl/commit/bb4369beaee22e1e16eec45e892e527d1a258ccb

Having 18.7 (last version in raspbian-repo), I'm wondering when there was a change from xbmc.translatePath to xbmcvfs.translatePath, since I'm getting errors, that xbmcvfs.translatePath is unknown.

btw. what seems to be a bug: it shouldn't be xbmcvfs.translatepath, but instead xbmcvfs.translatePath. Path should start with a capital letter no matter if xbmcvfs or xbmc.

Anyway for my 18.7 kodi I needed to change xbmcvfs.translatepath to xbmc.translatePath to get iagl working

**Comment by zach-morris** [comment]
Yes, this is an issue between Kodi v19 and v18.  I went round and round about how to approach this.  The change to python 3 is big enough that I just decided to update the addon completely for v19.

V19 branch is [here](https://github.com/zach-morris/plugin.program.iagl/tree/v19).  I should have it ready in roughly the same period of time that Kodi v19 is available.  The main branch here will then be moved to a v18 only branch where it will still be available, but I won't update it (apart from maybe updating game lists if they no longer work).

Closing this for now.  This is fixed in the 19 branch
