### ISSUE TITLE
SUGGESTION: Sort Games by Region/Language

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#214]
I've been playing a bit of Turbo Graphics CD games recently and noticed the vast majority are in Japanese.
What would really help me out is if there were some kind of sort function that made it so only games of a certain language appeared on the list.
Something that I wouldn't have to input all the time always would be good; that is to say, I set it once to display only English games and then I never have to set it again.

**Comment by zach-morris** [comment]
The best way to do this is by Tag, but thats highly dependent on the source game list.  Since most are either no-intro or redump, it works for the most part.  For PCE CD it should work:
Open the game list>Sort by Tag

<img src="https://cdn.discordapp.com/attachments/696566456464441367/821836318823677952/Screen_Shot_2021-03-17_at_1.03.11_PM.png">

Or if you're looking for multiple tags or a set it / forget it method:
Search>Choose Game List(s)>Filter by Tags and select multiple tags>Generate Search Link>Add to Favorites or IAGL Favorites
<img src="https://cdn.discordapp.com/attachments/696566456464441367/821836823575396362/Screen_Shot_2021-03-17_at_1.05.37_PM.png">

**Comment by zach-morris** [comment]
Closing with some updated documentation in the wiki

**Comment by pirsir76** [comment]
"Open the game list>Sort by Tag> then choose whichever grouping you're interested in"
Okay thanks, I know how to do that and it helps.

"Or if you're looking for multiple tags or a set it / forget it method:
Search>Choose Game List(s)>Filter by Tags and select multiple tags>Generate Search Link>Add to Favorites or IAGL Favorites"
I've tried to do this but couldn't.
1. I don't know how to select multiple tags.
2. I don't know how to generate a search link.

**Comment by pirsir76** [comment]
Thanks Zach I understand it now. :D
