### ISSUE TITLE
Confusion on updating launchers for favorites

### ISSUE THREAD

**Issue by chrisc25** [zach-morris/plugin.program.iagl#233]
Hi Zach

I can swear by the flying the Spaghetti Monster I have followed your Wiki but I am stumped.
I am running Ubuntu and Kodi 19.3; I have installed IAGL.
Now I have installed retroarch both genesis and snes games I have tried run (bios installed and all cores for all emulators) 
(I added SNES and Genesis roms via the retroarch scanner).

I installed IAGL from your repo, followed your wiki for a external setup.
In Configure - I have Linux enabled and the paths:

APP:    /usr/bin/retroarch
Config:   /home/chris/.config/retroarch/retroarch.cfg

In the 4th part of your walkthrough - I tried setting up "Select Launcher" on my favourites menu
External Launch Command
It updates and clears cache, then presents me lots of retro arch (I assume these are the cores)
If I select Retroarch Sega - GG/MS/MD/CD/32X (PicoDrive) 

Next I load the Mega Drive Sonic, and I get:
"This game isn't compatible with any available emulators"

Same story with Super Mario World and the retroarch Snex 9X current

Please can you help or suggest what I need to do next?

**Comment by chrisc25** [comment]
Sorry I have realised what I have done, they work if you select the launcher from the repository list things, 

I had a favourites menu called Sega childhood favourites and that wasn't allowing me to change the core, using the Select Launcher.  

I'm going to leave this open for you to consider if its a bug (select launcher on favourites which doesn't seem to work), or Ive not understood something.  

But wow awesome work!!

**Comment by zach-morris** [comment]
I think i understand.  Favorites are more or less hyperlinks to games in other lists.  I agree i should make a message pop up that says something to the effect of "You need to change the launcher in the original list", or something along those lines.

**Comment by zach-morris** [comment]
This functionality is updated for IAGL v4.0.  Favorites are still linked to their parent, however, you can change game list launchers directly from a favorite, and you will be alerted on what exactly your changing.  However, changing settings is now at least directly available from the game instead of navigating through the menus, which makes things easier:
<img width="841" alt="Screen Shot 2024-12-27 at 8 05 31 PM" src="https://github.com/user-attachments/assets/8df86d27-fdd1-4473-9106-803b0b73ffa9" />
