### ISSUE TITLE
Keeps exiting out everytime the game starts

### ISSUE THREAD

**Issue by Loading617** [zach-morris/plugin.program.iagl#259]

**Comment by zach-morris** [comment]
I'm gonna need more than that.  Like a debug log, steps to reproduce etc.

If I had to wager a guess, you're on Android and you're launching Retroarch External.  Depending on your system, some cores may be installed, some not, etc.  See the generic troubleshooting steps [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#14b-i-pressed-launch-but-nothing-happened-your-addon-is-broken).

**Comment by Loading617** [comment]
I'm running it on firestick

**Comment by zach-morris** [comment]
Android launching is fixed in 3.0.7 -  the wiki will have to be updated but there are some caveats. Main one being that the files need to be downloaded to a shared directory (one that both apps can see given their permissions). The wizard is updated to account for this. Let me know if you run into any issues.
