### ISSUE TITLE
Does not work on kodi 20.0

### ISSUE THREAD

**Issue by IAmAGitHubb** [zach-morris/plugin.program.iagl#268]
IAGL And the respotory does not work, can't get older version of kodi on SamsungGalaxy S6 Lite due to error, Package invalid or somthing

**Comment by doctornono** [comment]
I have same problem with Kodi 20.
Error with dependancy youtube installation,

**Comment by IAmAGitHubb** [comment]
I don't have that error, weird

**Comment by IAmAGitHubb** [comment]
Lemme test

**Comment by IAmAGitHubb** [comment]
I can't acess the respitory

**Comment by zach-morris** [comment]
This should be fixed with the latest repository and IAGL v 3.0.7- the wiki will have to be updated but there are some caveats. Main one being that the files need to be downloaded to a shared directory (one that both apps can see given their permissions). The wizard is updated to account for this. Let me know if you run into any issues.
