### ISSUE TITLE
Commodore 64 List error

### ISSUE THREAD

**Issue by Leon1016969** [zach-morris/plugin.program.iagl#304]
Hi Zack i have many issues on iagl with commodore platforms but i think is because of my bad.
Every time i try to see c64 list the program return to me a error message......so i can't go inside
also in amiga list i have problems......but there i can watch correctly lists but not play them.
![2023-12-03_15-23-02](https://github.com/zach-morris/plugin.program.iagl/assets/126110314/751a6487-4691-45c7-bf01-17ad5801f9bd)

**Comment by progtronix** [comment]
hello, i ran into problems like this and a few lists do the same thing but i applied this temp fix and it worked for me. maybe you can try the same to see if it helps until zach gets back to this project to release an update, the fix is another bug report listed here but i will link the comment below...

https://github.com/zach-morris/plugin.program.iagl/issues/286#issuecomment-1551775488

**Comment by Leon1016969** [comment]
u are so kind but i couldn' t understand this comment  at all"In resources/lib/utils.py commenting out line 980 and 981 then uncommenting line 982 solves issue for me"
could be u so gentle to let me understand me how fix it?
i found file address but i can't reach to open and fix it
