### ISSUE TITLE
Game images?

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#40]
Where are the images used by this add-on coming from? I see filenames in the .xml files, but where are they based?

**Comment by drinfernoo** [comment]
I figured out that they're Imgur ID's, but where do they come *from*? Do you have to go find them? Is there any type of standard sizes for various game images?

**Comment by zach-morris** [comment]
Most are (now) mirrored and sourced on imgur for speed and reliability.  Originally, i had made some homemade scrapers to gather game info from thegamesdb, mobygames, giantbomb, and a few others.   For that reason there really is no standardization at this point (and there are even plenty of errors).  I think eventually it makes sense to rescrape the images from a better/more reliable source and then try and mirror the images again to imgur and/or archive.org.  The sources I find are the best are:
launchboxdb
thegamesdb
screenscraper

But I'm open to other options.  The only requirement really is a reliable way to get the information from the source.

**Comment by drinfernoo** [comment]
Why not just use TheGamesDB's API to pull them directly into the add-on? It seems like everything you're curating into .xmls could be gathered directly from the DB much easier. I thought to try and take a look at what you've got going on, but I got a bit lost in the code.

**Comment by zach-morris** [comment]
If you look at the xml history (of IARL0, thats pretty much what it did.  Then the gamesdb started having server issues and the reliability of getting the images was pretty poor - this was true of pretty much any tool or frontend that was using thegamesdb.  Granted, they've been updated since then, but they do go down from time to time.  imgur on the other hand is reliably up, and traffic from the linked images is a drop in the bucket for imgur.  The images are statically linked since they're retro games, and the information itself should be more-or-less static.  It's really the reason this addon seems so fast as well, because everything is 'pre-scraped'.  The list of games would be orders of magnitude slower to be listed and populate if it had to ping an API that many times over and over.

**Comment by drinfernoo** [comment]
Totally fair. I was hoping to save you some trouble, but it seems it probably is better with the current solution ;) No worries.
