### ISSUE TITLE
[Request] More view consistency

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#5]
Most of the time, when I browse the add-on, I like to have consoles displayed with a "Banner Wall" view, but games displayed differently. However, since they are both classed as "TV shows" in Kodi, when I change the view for one, it changes the others 😒

Also, would it be possible to have different lists have different views? For example, to have square views for GB or PSX games, but landscape views for N64?

If I knew where this type of thing is in code, or how my changes may affect it, I'd fork and jump in, but I'm afraid I'll just screw it up 😂

**Comment by zach-morris** [comment]
What version of Kodi are you using?  I'm using the latest Kodi v18 alpha, with plain estuary, and it remembers the last used viewtype.  Attached is an example.  I have boxart view for SNES and banner view for TG16, and it remembers what I had selected if I leave the list and return to it.

<img width="719" alt="screen shot 2018-07-16 at 6 06 53 pm" src="https://user-images.githubusercontent.com/12554283/42791068-23430e4a-8923-11e8-82c2-a287c3cd244e.png">
<img width="718" alt="screen shot 2018-07-16 at 6 07 04 pm" src="https://user-images.githubusercontent.com/12554283/42791069-237d1fa4-8923-11e8-8c7a-037973ad551b.png">

**Comment by drinfernoo** [comment]
I'm actually on SPMC 17.6a2, with [https://forum.kodi.tv/showthread.php?tid=328558](Aura).

**Comment by zach-morris** [comment]
It's possibly changeable in the skins MyVideoNav.xml
https://forum.kodi.tv/showthread.php?tid=164048

**Comment by drinfernoo** [comment]
I think I'm asking for the opposite? To be able to set the view per list, rather than a default for all.

**Comment by NerdFlix** [comment]
If I'm not wrong, in order to set the view type you use the built in function `xbmc.executebuiltin("Container.SetViewMode(ID)")` where the ID is the view type you wanna set up. I used the ids below to set up view types depending on screen, but you can set it using addon settings.xml. if you don't want to code you can use Super favourite addon, it has an option to remember the last view type for each screen(Remember current view type), you can see this option on youtube video below.

**Youtube example setting view type with super favorite:**
https://youtu.be/iL-kFcKklCQ?t=598

**IDs for each viwe types:**
```
Plain list
xbmc.executebuiltin("Container.SetViewMode(50)") 

Big list
xbmc.executebuiltin("Container.SetViewMode(51)")

Icons
xbmc.executebuiltin("Container.SetViewMode(500)")

Poster list
xbmc.executebuiltin("Container.SetViewMode(501)")

Fanart list
xbmc.executebuiltin("Container.SetViewMode(508)")

Media Info 1
xbmc.executebuiltin("Container.SetViewMode(504)")

Media Info 2
xbmc.executebuiltin("Container.SetViewMode(503)")

Media Info 3
xbmc.executebuiltin("Container.SetViewMode(515)")
```
**It seems that for Kodi 18 you need a click event to set the view type:**
https://forum.kodi.tv/showthread.php?tid=329208

**Example code from the same thread:**
https://www.dropbox.com/s/l7koa2p1s93p0ap/script.test.builtinlist-1.0.2.zip?dl=0

**Comment by zach-morris** [comment]
OK, thanks for that info.  I could potentially add another game list option for default viewtype and have it set if defined.  However, I'm still not thinking its necessary.  I just loaded up Aura (which is pretty nice!) and it also remembers the viewtype that was set by each list - two different lists show two different viewtypes and they seem to be both remembered when I return.  Or am I missing something?

**Comment by drinfernoo** [comment]
I'll keep playing with it... maybe I'm setting my views wrong.

**Comment by zach-morris** [comment]
@drinfernoo just confirming this is skin specific before closing?  I noted in Aura there is a '[lock view](https://forum.kodi.tv/showthread.php?tid=328558&pid=2721657#pid2721657)' option in the context menu's.  It's possible this setting is messing up your views

**Comment by drinfernoo** [comment]
@zach-morris I do believe it is probably a skin issue.
