### ISSUE TITLE
Error in Show Info page and kodi favorites

### ISSUE THREAD

**Issue by Intel11** [zach-morris/plugin.program.iagl#54]
Hello:

When I launch a game (for example Mame 2003 - Galaxian) from kodi favorites and I have the value in IAGL: Default action when selecting a game: Show info page

Load the normal game in retroarch and then close retroarch to return to Kodi, Kodi freezes and closes.

But if the option is: Download and launch

When I close retroarch to return to Kodi, Kodi works normal.

Android 7.1.2 kodi freezes (Kodi 17.6 and Kodi 18.1)
Windows 7 64 bit kodi works normal (Kodi 18.0)
IAGL: 2.0.7

It seems to me that when it is: Show info page, IAGL tries to return to the list of games when it leaves retroarch. And since there is no list of games, since in kodi favorites there is only "the game", it freezes.

Thank you

**Comment by zach-morris** [comment]
I tried what you're suggesting.  Created a new Kodi Favorite for Galaxian, which opens the info window, launched it externally (and with Retroplayer) and then closed Retroarch and Kodi just takes me back to the same screen, and no freezing.

Then tried download and launch, launched externally (and with Retroplayer) and then closed Retroarch.  Kodi just took me to the home screen.

So I get the same response in both cases.  Maybe it's an Android only thing?  I'm guessing it's a Kodi bug rather than an addon bug, but I'd need a debug logfile of the freezing occuring to know for sure.

**Comment by Intel11** [comment]
Hi, thanks for answering.

Here I send the log of kodi on android, I hope it helps you to see the problem. Your tests have been on Android?

I am sending several log.

The files that have: F (they are the ones that stay frozen and use: Show Info Page)
The files that have: N (they are the ones that do NOT stay frozen and use: Download and Launch)

Thank you.
[iagl.zip](https://github.com/zach-morris/plugin.program.iagl/files/2894271/iagl.zip)

**Comment by zach-morris** [comment]
This may be a kodi bug, specific to android.  See [here](https://forum.kodi.tv/showthread.php?tid=338000&page=2).

There may be a workaround:
```
"Allow remote control from applications on this system" under "Services" has to be turned off, otherwise Kodi 18 crashes
```

**Comment by Intel11** [comment]
Hello, but this also happens to me in kodi 17.6 on android.

I'll try it later and I'll let you know.

Thank you.

**Comment by zach-morris** [comment]
This was likely related to #118, so I'm closing this issue.  If possible please give this another try using the latest master from github

**Comment by Intel11** [comment]
Hello, sorry for the delay in responding, I tried it on kodi 17 and kodi 18 and it works perfectly, thanks for repairing it.

**Comment by Intel11** [comment]
Hello, sorry for the delay in answering, I tried it on kodi 17 and kodi 18 and it works perfect, thank you very much for repairing it.
