### ISSUE TITLE
Feature Request: put custom list in a separate parent directory

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#96]
Custom List should be at the same level as "Browse Game Listing" for quick access. 
At the moment CustomLists are in between all other list make it hard to browse unless you either rename them _MyList1 ( So all List start with a speical char ) or hide all other lists

**Comment by zach-morris** [comment]
Well thats technically what categories are for.  You can make your own custom category by selecting your list, bringing up the context menu and then select 'Update Metadata', then choose 'Category'.
You can enter anything you want in for a category:
<img src="https://i.imgur.com/W0ScrtX.png" width="300" height="300">

Then when you browse by category, your new category will be listed:
<img src="https://i.imgur.com/iJ1hu82.png" width="300" height="300">

**Comment by Philps** [comment]
Hi Zach, thats exactly what i meant. the Category is in the main list and if i dont use widgets, i have to search for my category unless i hide all others. 

the request is to elevate the "my category/custom list" and directory on top, next to browse all

**Comment by zach-morris** [comment]
I can't think of a clean way to do this, since there's nothing particular identifying 'custom lists' at this point.  I might be able to make a top level directory 'Browse by Author' so you can organize the lists by the author of the list, but at this point, that would 99% be the default lists so it makes no sense to have it now.  Maybe if/when I re-implement a community list sharing function I will add this.

In addition, there's lots of other tools readily available to mix/match/display/organize stuff in Kodi.  Aside from Favorites, you've got [Super Favorites](https://forum.kodi.tv/showthread.php?tid=192662) and then various skins have infinite ways to organize.
